Dev
kr-colab/popvae pull request #23
Opened 2024-04-03 04:08 UTC by cjbattey

This PR updates the build system and installation instructions. This setup worked for a fresh install on an M3 MacBook, using mamba for the virtual environment. 

Changes: 
- switch from setup.py to hatchling for package builds
- swith from setup.py to pip install ./ for package installation
- upgrade tensorflow and keras to v2.15 and python to 3.10 (surprisingly this involved no api changes to the network code, phew)
-  update README with new installation instructions

I tried to get this working with smaller tweaks I think five separate times and kept getting sucked in to more and more confusing dependency issues. But python 3.7 and tensorflow 1 are dropping off pip, so have to update. I think (hope) this one will work. 

@andrewkern , any chance you or someone in the lab could give this a shot and see if they can install and run the test data?

2024-04-03 14:50 UTC, andrewkern commented
yo @cjbattey! thanks for doing this. I'll definitely look through it in the next day or so. seems like a lot of code moved here-- mostly auto-reformatting?

2024-04-03 15:05 UTC, cjbattey commented
Thanks! Yes, almost all black reformat and build stuff. popvae.py also moved to the top level directory to work with the new build system. But there were no changes in popvae.py code other than import commands to work with a newer Keras version.

2024-04-05 21:46 UTC, andrewkern requested changes
I hit an error running the test example using the `--seed` flag. I think it's a simple enough fix @cjbattey

2024-04-05 21:46 UTC, andrewkern commented on popvae.py
> +    tensorflow.set_random_seed(seed)
this is throwing an error on the example in the readme. I think this call has been changed to `tf.random.set_seed()`

2024-04-09 06:08 UTC, cjbattey commented
oops, sorry about that. Fixed now, and I added a `--test` function. Please pull and give it another shot with `python popvae.py --test` (shouldn't need to reinstall).

2024-04-23 01:29 UTC, merged